### ISSUE TITLE
swagger  도입

### ISSUE THREAD

**Issue by EvansKJ57** [PHJ-a/steam-todolist-backend#24]
### 제안이유 (장점)

- API 문서 작성이 쉬워지고 기존 방식은 코드 작성 후 wiki를 업데이트해야 하는 번거로움이 있는데 Swagger를 이용하면 코드 작성하면서 API 문서도 같이 작성할 수 있어서 편합니다.
- Swagger가 제공하는 문서에서는 직접 응답 테스트를 해볼 수 있습니다. (Postman을 사용해서 확인하거나 프론트엔드 프로젝트와 연결해서 확인하는 방법보다 편합니다.)

### 단점
- 데코레이터가 늘어나서 코드 가독성이 안 좋아질 수 있습니다.

### 참고자료
- [공식문서](https://docs.nestjs.com/openapi/introduction)
- [블로그](https://choiblog.tistory.com/46) => 블로그에서는 단점을 상쇄하기 위해 플러그인을 사용했지만 현재 프로젝트에서는 굳이 플러그인까지 사용할 필요는 없어 보입니다.

**Comment by gjeodnd12165** [comment]
좋습니다. 

일일이 수정하는것 보다는 자동화하는 게 더 낫다고 생각합니다.
